### PR TITLE
I am not understanding why the hell is it showing a error in the RUNNING 

### PR DESCRIPTION
**Pull request by Twlightzone**
tbh i tried `npm run dev` and it did work now! sooo just see the thing like the GITIGNORE and README then commit

### CODE REVIEW

**Comment by Aradhya-Shaswat** [comment]
Do you really want to **merge** it?

**Comment by Twlightzone** [comment]
Not much but honest work :)

**Comment by Twlightzone** [comment]
Also Arsh its not deadly I just removed this workspace thing and it *should* be fine now :)

**Comment by Twlightzone** [comment]
Arsh I made the Read me good again this time PLEASE U MF JUST ADD IT AND FUCKING GIVE UR GMAIL AND NUMBER THERE

**Comment by Twlightzone** [comment]
Alright moron, I have Changed the Readme.md (cuz u said so) Its very very nice and also Just Dont press the link i provided.

Its from the victims of those who shall press the link.

- Armaan Given at 10pm cuz i dont need sleep and will be here till 4am :)

**Comment by Twlightzone** [comment]
Also mate I will recommend u to give me the .env.development token otherwise, well, i will tell *her*

**Pull request merged**
